<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1179" started-at="2017-12-19T07:36:04Z" finished-at="2017-12-19T07:36:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1179" started-at="2017-12-19T07:36:04Z" finished-at="2017-12-19T07:36:05Z">
      <class name="com.lu.LUAutoSpace.huizhitong.TestMoney">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.lu.LUAutoSpace.huizhitong.TestMoney@2d928643]" name="beforeClass" is-config="true" duration-ms="703" started-at="2017-12-19T15:36:04Z" finished-at="2017-12-19T15:36:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="test()[pri:0, instance:com.lu.LUAutoSpace.huizhitong.TestMoney@2d928643]" name="test" duration-ms="454" started-at="2017-12-19T15:36:04Z" finished-at="2017-12-19T15:36:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [8531.36] but found [9560.36]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [8531.36] but found [9560.36]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:442)at com.lu.LUAutoSpace.huizhitong.TestMoney.test(TestMoney.java:112)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.lu.LUAutoSpace.huizhitong.TestMoney@2d928643]" name="afterClass" is-config="true" duration-ms="1" started-at="2017-12-19T15:36:05Z" finished-at="2017-12-19T15:36:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.lu.LUAutoSpace.huizhitong.TestMoney -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
